sudo: false
language: java
services:
  - docker
cache:
  directories:
    - "$HOME/.m2/repository"
jdk:
  - openjdk8

script:
  - chmod +x .travis/mvn-deploy.sh
  - mvn clean
  - mvn install
after_success:
  - mkdir push
  - cp ./advancedregionmarket/target/*.jar ./push
  - rm -f ./push/original-*.jar
  - rm -f ./push/*-shaded.jar
  - rm -f ./push/*-sources.jar
  - mv -f ./push/*-javadoc.jar ./push/JavaDocument.zip
deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    file:
      - ./push/*
    file_glob: true
    skip_cleanup: true
    on:
      tags: true
    overwrite: true